#!/usr/bin/env python3
"""Build the eight selected CVPR table assets without importing measurements.

Only Python's standard library is required. Run from any working directory:
    python paper/scripts/build_draft_tables.py

The table bodies intentionally contain only ``\\textemdash`` measurement cells.
Sequence identifiers, allowed time scales, and sampling budgets are structural
labels, not reported results. Existing experiment CSVs are never read.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


PAPER = Path(__file__).resolve().parents[1]
ROOT = PAPER.parent
PLAN = PAPER / "plan" / "visual_assets"
EMPTY = r"\textemdash"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def md_cells(line: str) -> list[str]:
    return [part.strip() for part in line.strip().strip("|").split("|")]


def read_methods() -> list[dict[str, object]]:
    rows = []
    for line in (PLAN / "baseline_registry.md").read_text().splitlines():
        if not line.startswith("|"):
            continue
        cells = md_cells(line)
        if len(cells) == 4 and cells[1] in ("RGB", "RGB+IMU"):
            rows.append({"name": cells[0], "input": cells[1], "conditional": False})
    assert len(rows) == 9, "Expected the nine confirmed registry candidates."
    conditional_name = "MM3DGS-SLAM"
    assert conditional_name in (PLAN / "baseline_registry.md").read_text()
    rows.append({"name": conditional_name, "input": "mono+IMU (conditional)", "conditional": True})
    return rows


def read_datasets() -> dict[str, list[str]]:
    datasets = {}
    for line in (PLAN / "dataset_registry.md").read_text().splitlines():
        if not line.startswith("|"):
            continue
        cells = md_cells(line)
        if len(cells) == 2 and cells[0] in ("RPNG", "UTMM", "Aria"):
            datasets[cells[0]] = [name.strip() for name in cells[1].split(",")]
    assert [len(seq) for seq in datasets.values()] == [8, 8, 4]
    return datasets


METHODS = read_methods()
DATASETS = read_datasets()
METRICS = [
    ("psnr", r"PSNR $\uparrow$"),
    ("ssim", r"SSIM $\uparrow$"),
    ("lpips", r"LPIPS $\downarrow$"),
    ("gaussians_k", r"\#G (k)"),
]
LEGEND = (
    r"\textsuperscript{VI}: RGB+IMU; \textsuperscript{R}: RGB only. "
    r"\textsuperscript{C}: conditional monocular+IMU MM3DGS-SLAM adapter, "
    r"pending verification without sensor depth. "
    r"\textemdash{} = unmeasured. No cell is a reported result."
)
COHORT_NOTE = (
    r"Valid paired cohort $n/N=$\textemdash/\textemdash{} for every dataset and method. "
    r"Dataset means will give equal weight to scene means; no failed or missing scene "
    r"has been silently excluded."
)


def escape(text: str) -> str:
    return text.replace("_", r"\_").replace("%", r"\%")


def method_tex(method: dict[str, object]) -> str:
    name = escape(str(method["name"]))
    if name == "Ours":
        name = r"\textbf{Ours}"
    mark = "C" if method["conditional"] else ("VI" if method["input"] == "RGB+IMU" else "R")
    return name + rf"\textsuperscript{{{mark}}}"


def sequence_head(name: str) -> str:
    """Keep full registry identifiers while wrapping the widest headings."""
    if name.startswith("table_"):
        return r"\shortstack{table\\\_" + name.split("_")[1] + "}"
    if name.startswith("ego-centric-"):
        return r"\shortstack{ego-\\centric-" + name.rsplit("-", 1)[1] + "}"
    if name.startswith("slow-straight-"):
        return r"\shortstack{slow-\\straight-" + name.rsplit("-", 1)[1] + "}"
    if name == "fast-straight":
        return r"\shortstack{fast-\\straight}"
    if name.startswith("aria301_"):
        return r"\shortstack{aria301\\\_" + name.split("_")[1] + "}"
    return escape(name)


def row(cells: list[str]) -> str:
    return " & ".join(cells) + r" \\"


def table(
    caption: str,
    labels: list[str],
    columns: str,
    headers: list[str],
    body: list[str],
    *,
    full_width: bool = False,
    font: str = r"\small",
    notes: str = "",
    tabcolsep: str = "4pt",
) -> str:
    env = "table*" if full_width else "table"
    placement = "tbp" if full_width else "htbp"
    width = r"\textwidth" if full_width else r"\linewidth"
    return "\n".join(
        [
            "% Generated by paper/scripts/build_draft_tables.py; measurements intentionally blank.",
            rf"\begin{{{env}}}[{placement}]",
            r"\centering",
            r"\caption{\textbf{DRAFT blank template; no measurements.} " + caption + "}",
            *[rf"\label{{{label}}}" for label in labels],
            r"\begingroup",
            font,
            rf"\setlength{{\tabcolsep}}{{{tabcolsep}}}",
            r"\renewcommand{\arraystretch}{1.06}",
            rf"\resizebox{{{width}}}{{!}}{{%",
            rf"\begin{{tabular}}{{@{{}}{columns}@{{}}}}",
            r"\toprule",
            row(headers),
            r"\midrule",
            *body,
            r"\bottomrule",
            r"\end{tabular}}",
            r"\endgroup",
            *([
                r"\par\vspace{4pt}",
                rf"\begin{{minipage}}{{{width}}}",
                r"\scriptsize\raggedright " + notes,
                r"\end{minipage}",
            ] if notes else []),
            rf"\end{{{env}}}",
            "",
        ]
    )


def main_rendering() -> tuple[str, list[str], dict[str, object]]:
    body = []
    for dataset_idx, dataset in enumerate(DATASETS):
        if dataset_idx:
            body.append(r"\midrule")
        for method_idx, method in enumerate(METHODS):
            body.append(row([dataset if method_idx == 0 else "", method_tex(method), *([EMPTY] * 4)]))
    labels = ["tab:rendering_comparison", "tab:main"]
    caption = (
        "Planned rendering comparison on RPNG, UTMM, and Aria at a matched absolute "
        "training-render budget. Held-out PSNR, SSIM, LPIPS, and checkpoint Gaussian "
        "counts will be aggregated from the same sequence records as the appendix. "
        "The proposed recipe, budget, and evaluation cohort remain to be locked."
    )
    tex = table(caption, labels, "llcccc", ["Dataset", "Method", r"PSNR $\uparrow$", r"SSIM $\uparrow$", r"LPIPS $\downarrow$", r"\#G (k)"], body, notes=LEGEND + " " + COHORT_NOTE)
    return tex, labels, {"data_rows": 30, "measurement_columns": 4, "float_count": 1}


def supplementary_rendering(time_comparison: bool = False) -> tuple[str, list[str], dict[str, object]]:
    pieces = []
    labels = []
    for dataset, sequences in DATASETS.items():
        scales = [("1x", r"$1\times$"), ("1p5x", r"$1.5\times$")] if time_comparison else [("", "")]
        for scale_key, scale_label in scales:
            current_labels = [f"tab:t{'2' if time_comparison else '1'}_supp_{dataset.lower()}" + (f"_{scale_key}" if scale_key else "")]
            if not labels and not time_comparison:
                current_labels.insert(0, "tab:scene")
            labels.extend(current_labels)
            body = []
            for metric_idx, (_, metric_tex) in enumerate(METRICS):
                if metric_idx:
                    body.append(r"\midrule")
                for method in METHODS:
                    body.append(row([metric_tex, method_tex(method), *([EMPTY] * (len(sequences) + 1))]))
            allowance = f" at {scale_label} input-time allowance" if time_comparison else " at the matched training-render budget"
            caption = (
                f"Planned sequence-level rendering comparison for {dataset}{allowance}. "
                "All registered sequences and methods are retained. Avg. will be the "
                "equal-weight mean over a disclosed paired cohort, using the same "
                "records as the corresponding main table."
            )
            if time_comparison:
                caption += " Tracking and mapping run together; mapper zero-tail and tracker lag are separate conditions."
            pieces.append(table(caption, current_labels, "ll" + "c" * (len(sequences) + 1), ["Metric", "Method", *[sequence_head(name) for name in sequences], "Avg."], body, full_width=False, font=r"\fontsize{8}{9.2}\selectfont", notes=LEGEND + " " + COHORT_NOTE, tabcolsep="2.5pt"))
    metadata = {"quality_rows": 40 * (6 if time_comparison else 3), "quality_float_count": 6 if time_comparison else 3, "metrics": [key for key, _ in METRICS]}
    return "\n\n".join(pieces), labels, metadata


def main_time() -> tuple[str, list[str], dict[str, object]]:
    pieces = []
    labels = []
    for scale_key, scale_label in [("1x", r"$1\times$"), ("1p5x", r"$1.5\times$")]:
        current_labels = [f"tab:time_comparison_{scale_key}"]
        if not labels:
            current_labels.insert(0, "tab:time_comparison")
        labels.extend(current_labels)
        body = []
        for dataset_idx, dataset in enumerate(DATASETS):
            if dataset_idx:
                body.append(r"\midrule")
            for method_idx, method in enumerate(METHODS):
                body.append(row([dataset if method_idx == 0 else "", scale_label if method_idx == 0 else "", method_tex(method), *([EMPTY] * 5)]))
        caption = (
            f"Planned end-to-end quality comparison with {scale_label} input-time allowance. "
            "The allowance multiplies the sensor duration and slows input release; it is "
            "not faster sensor playback. Tracking and mapping share the hardware and "
            "deadline. Input lag remains visible even when mapper optimizer tail is zero."
        )
        pieces.append(table(caption, current_labels, "lllccccc", ["Dataset", "Allowance", "Method", r"PSNR $\uparrow$", r"SSIM $\uparrow$", r"LPIPS $\downarrow$", r"\#G (k)", r"\shortstack{Input lag\\p95 (s)}"], body, font=r"\fontsize{8.5}{9.8}\selectfont", notes=LEGEND + " " + COHORT_NOTE))
    return "\n\n".join(pieces), labels, {"data_rows": 60, "measurement_columns": 5, "float_count": 2}


def supplementary_runtime() -> tuple[str, list[str], dict[str, object]]:
    pieces = []
    labels = []
    # The selected layout requests runtime details for the direct VIGS/Ours pair.
    direct_methods = [method for method in METHODS if method["name"] in ("VIGS-SLAM", "Ours")]
    for dataset, sequences in DATASETS.items():
        label = f"tab:t2_runtime_{dataset.lower()}"
        labels.append(label)
        body = []
        for sequence_idx, sequence in enumerate(sequences):
            if sequence_idx:
                body.append(r"\addlinespace[1pt]")
            for scale_label in [r"$1\times$", r"$1.5\times$"]:
                for method in direct_methods:
                    body.append(row([dataset, escape(sequence), scale_label, method_tex(method), *([EMPTY] * 8)]))
        caption = (
            f"Planned detailed runtime accounting for every registered {dataset} sequence "
            "and both input-time allowances, using the direct VIGS-SLAM/Ours pair. "
            "Training renders, additional geometry forwards, and successful Adam steps "
            "are distinct work units. Drops and optimizer tail are unmeasured counts, "
            "not assumed zeros."
        )
        headers = ["Dataset", "Sequence", r"\shortstack{Allow-\\ance}", "Method", r"\shortstack{Deadline\\(s)}", r"\shortstack{Tracking\\elapsed (s)}", r"\shortstack{Lag\\p95 (s)}", r"\shortstack{Training\\renders}", r"\shortstack{Extra geom.\\renders}", r"\shortstack{Adam\\steps}", "Drops", r"\shortstack{Tail\\updates}"]
        pieces.append(table(caption, [label], "llll" + "c" * 8, headers, body, full_width=False, font=r"\fontsize{7}{8.2}\selectfont", notes=r"\textsuperscript{VI}: RGB+IMU. \textemdash{} = unmeasured. Deadline is relative to sensor release start; clock origin, warmup, synchronization, save/evaluation overhead, and tracker configuration must be recorded before results are inserted.", tabcolsep="1.5pt"))
    return "\n\n".join(pieces), labels, {"runtime_rows": 80, "runtime_float_count": 3, "runtime_methods": [method["name"] for method in direct_methods], "runtime_measurement_columns": 8}


def geometry_table() -> tuple[str, list[str], dict[str, object]]:
    labels = ["tab:geometry"]
    body = [row([EMPTY, method, *([EMPTY] * 6)]) for method in ["VIGS-SLAM", "Ours w/o geometry", "Ours with geometry"]]
    caption = (
        "Planned geometry comparison with VIGS-SLAM and the proposed mapper with and "
        "without the final geometry objective. Scene/reference selection, distance "
        "units, F-score threshold, extraction rule, and visibility mask are pending. "
        "Accuracy and completeness distances must use an independent reference; "
        "held-out RGB quality and map size will be reported beside free-space error."
    )
    headers = ["Dataset / scene", "Method", r"Accuracy $\downarrow$", r"\shortstack{Completeness\\$\downarrow$}", r"F-score $\uparrow$", r"\shortstack{Free-space\\error $\downarrow$}", r"PSNR $\uparrow$", r"\#G (k)"]
    tex = table(caption, labels, "llcccccc", headers, body, font=r"\fontsize{8}{9.3}\selectfont", notes=r"\textemdash{} = unmeasured. These are reserved cells, including unknown scene identities. Unsupported independent-reference metrics must later be marked NA; training depth or PSNR alone will not establish geometric correctness.", tabcolsep="3pt")
    return tex, labels, {"data_rows": 3, "measurement_columns": 6, "float_count": 1, "scene_selection": "pending"}


def sampling_table() -> tuple[str, list[str], dict[str, object]]:
    labels = ["tab:order"]
    body = []
    for metric_idx, (_, metric_tex) in enumerate(METRICS[:3]):
        if metric_idx:
            body.append(r"\midrule")
        for policy in ["Random reshuffling (RR)", "ERCB (original replay)"]:
            body.append(row([metric_tex, policy, *([EMPTY] * 3)]))
    caption = (
        "Planned sampling comparison in the original RR versus ERCB replay regime. "
        "The three columns preserve the selected mapping-update budgets per "
        "keyframe interval. All endpoints must come from paired runs with the same "
        "causal input, initialization, loss, topology, and cohort. No historical "
        "reported value has been carried into this template."
    )
    headers = ["Metric", "Sampling policy", r"\shortstack{15 updates\\per interval}", r"\shortstack{30 updates\\per interval}", r"\shortstack{60 updates\\per interval}"]
    tex = table(caption, labels, "llccc", headers, body, notes=r"\textemdash{} = unmeasured. Original ERCB is not automatically interchangeable with the current cumulative per-view ERVS implementation; newer renderer-budget panels require separate identification.")
    return tex, labels, {"data_rows": 6, "measurement_columns": 3, "float_count": 1, "structural_budgets": [15, 30, 60]}


def dense_table() -> tuple[str, list[str], dict[str, object]]:
    labels = ["tab:abl"]
    body = []
    for dataset_idx, dataset in enumerate(DATASETS):
        if dataset_idx:
            body.append(r"\midrule")
        for policy_idx, policy in enumerate(["Keyframes only", "+ in-between frames"]):
            body.append(row([dataset if policy_idx == 0 else "", EMPTY, policy, *([EMPTY] * 4)]))
    caption = (
        "Planned supervision comparison between keyframes only and additional "
        "in-between RGB frames. Each dataset uses paired runs under the same "
        "code and budget, which remain unassigned here. Separate code or budget "
        "regimes must be reported as separate panels; no historical replay "
        "measurements have been inserted."
    )
    headers = ["Dataset", "Code / budget", "Supervision", r"PSNR $\uparrow$", r"SSIM $\uparrow$", r"LPIPS $\downarrow$", r"\#G (k)"]
    tex = table(caption, labels, "lllcccc", headers, body, font=r"\fontsize{8.5}{9.8}\selectfont", notes=r"\textemdash{} = unmeasured or an unassigned condition. Causal trace, poses, initialization, RGB loss, topology, sampler, and absolute render budget must be fixed for each pair; any quota or learning-rate-position mismatch must be disclosed.")
    return tex, labels, {"data_rows": 6, "measurement_columns": 4, "float_count": 1, "code_budget_assignment": "pending"}


def peak_table() -> tuple[str, list[str], dict[str, object]]:
    labels = ["tab:baseline_peak"]
    body = []
    for dataset_idx, (dataset, sequences) in enumerate(DATASETS.items()):
        if dataset_idx:
            body.append(r"\midrule")
        for sequence_idx, sequence in enumerate(sequences):
            body.append(row([dataset if sequence_idx == 0 else "", escape(sequence), *([EMPTY] * 6)]))
    caption = (
        "Planned scene-level cost of first reaching the VIGS-SLAM highest observed "
        "held-out PSNR on a common checkpoint grid and horizon. Baseline cost is "
        "the first checkpoint attaining that peak; proposed-method cost is the "
        "first checkpoint attaining or exceeding the same target. Every registered "
        "sequence is retained and all curve-derived measurements are blank."
    )
    headers = ["Dataset", "Sequence", r"\shortstack{VIGS peak\\PSNR}", r"\shortstack{VIGS renders\\to peak}", r"\shortstack{Ours renders\\to target}", r"\shortstack{Saved\\renders}", r"\shortstack{Reduction\\(\%)}", r"\shortstack{Final PSNR\\VIGS / Ours}"]
    notes = (
        r"\textemdash{} = unmeasured; NR will denote a target not reached within the "
        r"shared horizon. Saved renders are $u_{V,s}^{*}-u_{O,s}^{*}$ and reduction "
        r"is $100(1-u_{O,s}^{*}/u_{V,s}^{*})\%$; negative values will be retained. "
        r"Scene-level median reduction and reached $n/N$ will be summarized only "
        r"after measurement. Checkpoint crossings are measured grid points, without "
        r"unlabelled interpolation; zero baseline cost requires NA handling."
    )
    tex = table(caption, labels, "llcccccc", headers, body, font=r"\fontsize{8}{9.3}\selectfont", notes=notes, tabcolsep="3pt")
    return tex, labels, {"data_rows": 20, "measurement_columns": 6, "float_count": 1, "horizon_and_checkpoint_grid": "pending"}


def preview_source(appendix: bool) -> str:
    # Relative paths keep each source recompilable after a workspace relocation.
    return "\n".join([
        r"\documentclass[10pt,twocolumn,letterpaper]{article}",
        r"\usepackage[pagenumbers]{../../../latex/cvpr}",
        r"\usepackage{graphicx}",
        r"\usepackage{booktabs}",
        r"\usepackage{amsmath}",
        r"\begin{document}",
        r"\input{table.tex}",
        r"\clearpage",
        r"\end{document}",
        "",
    ])


def install_asset(asset: str, portable: str, result: tuple[str, list[str], dict[str, object]], *, appendix: bool = False) -> None:
    tex, labels, structure = result
    folder = PAPER / "tables" / asset
    current = folder / "current"
    current.mkdir(parents=True, exist_ok=True)
    previous = current / "provenance.json"
    if previous.exists():
        recorded = json.loads(previous.read_text())
        if recorded.get("experimental_evidence") or recorded.get("measurements_present"):
            raise RuntimeError(f"Refusing to replace measured {asset} with blank templates; use its measured-data builder.")
    (PAPER / "latex" / "tab").mkdir(parents=True, exist_ok=True)
    (current / "table.tex").write_text(tex)
    portable_path = PAPER / "latex" / "tab" / portable
    portable_path.write_text(tex)
    (current / "preview.tex").write_text(preview_source(appendix))
    captions = []
    for line in tex.splitlines():
        if line.startswith(r"\caption{"):
            captions.append(line[len(r"\caption{"):-1])
    (current / "caption.md").write_text(
        "# " + asset + " — draft captions\n\n"
        + "Status: **DRAFT blank template / no measurements**. All measurement cells are em dashes.\n\n"
        + "\n\n".join(f"{index + 1}. `{caption}`" for index, caption in enumerate(captions)) + "\n"
    )
    source_paths = [
        PLAN / "CURRENT.md", PLAN / "baseline_registry.md", PLAN / "dataset_registry.md",
        PLAN / "protocol.md", folder / "plan" / "CURRENT.md", Path(__file__).resolve(),
    ]
    provenance = {
        "asset_id": asset,
        "status": "draft_blank_template",
        "measurements_present": False,
        "created_date": "2026-10-01",
        "generation_command": "python paper/scripts/build_draft_tables.py",
        "generator": str(Path(__file__).resolve().relative_to(ROOT)),
        "portable_copy": str(portable_path.relative_to(ROOT)),
        "labels": labels,
        "required_packages": ["booktabs"],
        "float_environment": "table (one-column)",
        "float_placement": "htbp" if appendix else "tbp",
        "structure": structure,
        "measurement_placeholder": EMPTY,
        "methods": METHODS if asset.startswith(("table01", "table02")) else [],
        "datasets": DATASETS,
        "cohort_status": "unassigned; no results or averages computed",
        "run_ids": [],
        "experiment_data_files": [],
        "sources": [{"path": str(path.relative_to(ROOT)), "sha256": sha256(path)} for path in source_paths],
        "table_sha256": sha256(current / "table.tex"),
        "preview": {
            "source": "preview.tex",
            "expected_pdf": "preview.pdf",
            "expected_png": "preview-01.png",
            "compile_command": f"/tmp/cvpr_tools/tectonic {current.relative_to(ROOT)}/preview.tex --outdir {current.relative_to(ROOT)} --keep-logs",
            "uses_cvpr_dimensions": True,
        },
    }
    (current / "provenance.json").write_text(json.dumps(provenance, ensure_ascii=False, indent=2) + "\n")
    (current / "README.md").write_text(
        f"# {asset} — 빈칸 TeX 초안\n\n"
        "2026-10-01. **측정값 없는 DRAFT template**이며 결과 검증을 통과한 최종 표가 아니다. "
        "숫자 측정 칸은 모두 `\\textemdash`이고 기존 실험 결과를 가져오지 않았다. "
        "시간 배수·예산·sequence 이름에 포함된 숫자는 계획의 구조 라벨이다.\n\n"
        "- [표 TeX](table.tex) / [독립 미리보기 소스](preview.tex) / [PDF 미리보기](preview.pdf) / [첫 페이지 PNG](preview-01.png)\n"
        "- [Caption](caption.md) / [Provenance](provenance.json)\n"
        f"- 원고용 복사본: [latex/tab/{portable}](../../../latex/tab/{portable})\n"
        "- 재생성: `python paper/scripts/build_draft_tables.py`\n"
        f"- labels: {', '.join('`' + label + '`' for label in labels)}\n\n"
        + "본문과 부록 모두 한 단 너비의 `table` float로 입력한다. "
        + "사용 패키지는 `booktabs`이며 `\\shortstack`/`\\textemdash`는 LaTeX 기본 명령이다.\n"
    )
    (folder / "README.md").write_text(
        f"# {asset}\n\n[계획](plan/CURRENT.md) · [빈칸 TeX 초안](current/README.md)\n\n"
        "`current/`에는 2026-10-01 생성한 측정값 없는 초안이 있다. 모든 값은 공란이며 "
        "연구 결과 또는 최종 출판용 표의 완성을 뜻하지 않는다.\n"
    )


def main() -> None:
    install_asset("table01_rendering_main", "t1_main_draft.tex", main_rendering())
    install_asset("table01_rendering_supp", "t1_supp_draft.tex", supplementary_rendering(), appendix=True)
    install_asset("table02_time_main", "t2_main_draft.tex", main_time())
    quality, quality_labels, quality_structure = supplementary_rendering(time_comparison=True)
    runtime, runtime_labels, runtime_structure = supplementary_runtime()
    install_asset("table02_time_supp", "t2_supp_draft.tex", (quality + "\n\n" + runtime, quality_labels + runtime_labels, quality_structure | runtime_structure), appendix=True)
    install_asset("table03_geometry", "t3_geometry_draft.tex", geometry_table())
    install_asset("table04_sampling_budget", "t4_sampling_draft.tex", sampling_table())
    install_asset("table05_dense_supervision", "t5_dense_draft.tex", dense_table())
    install_asset("table06_baseline_peak", "t6_peak_draft.tex", peak_table())
    assets = [
        ("T1-main", "table01_rendering_main"), ("T1-supp", "table01_rendering_supp"),
        ("T2-main", "table02_time_main"), ("T2-supp", "table02_time_supp"),
        ("T3", "table03_geometry"), ("T4", "table04_sampling_budget"),
        ("T5", "table05_dense_supervision"), ("T6", "table06_baseline_peak"),
    ]
    (PAPER / "tables" / "README.md").write_text(
        "# CVPR tables — 빈칸 초안 자산\n\n"
        "2026-10-01. [통합 계획](../plan/visual_assets/CURRENT.md)에 선택된 8개 항목의 "
        "TeX 빈칸 초안을 만들었다. **측정값이 들어간 표는 아니며 모든 숫자 측정 칸은 공란이다.** "
        "기존 계획 및 실험 기록은 보존한다.\n\n"
        "| ID | 계획 | 현재 빈칸 초안 |\n|---|---|---|\n"
        + "\n".join(f"| {name} | [계획]({asset}/plan/CURRENT.md) | [TeX/caption/provenance]({asset}/current/README.md) |" for name, asset in assets)
        + "\n\n재생성: `python paper/scripts/build_draft_tables.py`. "
        "Portable TeX 복사본은 `paper/latex/tab/*_draft.tex`이며 원고가 이를 입력한다.\n"
    )
    print("Generated eight table assets; all measurement cells are blank.")


if __name__ == "__main__":
    main()
