Dataset:
  pcd_downsample: 256
  pcd_downsample_init: 64
  ppm_sampling: true
  adaptive_density: true
  adaptive_density_curve: "config/exp55/aria1253_content_curve.json"
  adaptive_density_growth_allowance: 2.0
  adaptive_pointsize: true
  point_size: 0.05
  scale_multiplier: 2.0

mono_model: omnidata

IMU:
  frequency: 400
  accelerometer_noise_density: 0.00207649074
  accelerometer_random_walk: 0.00041327852
  gyroscope_noise_density: 0.00020544166
  gyroscope_random_walk: 1.110622e-05
  imu_time_offset: 0.00252437791367
  rgb_file_in_nanoseconds: true
  imu_in_nanoseconds: true
  init_g: [0.0, 0.0, -9.81]
  init_bg: [0.0, 0.0, 0.0]
  init_ba: [0.0, 0.0, 0.0]
  Tcb_np:
    - [0.9999654398038452, 0.007342326779113337, -0.003899927610975742, -0.027534314618518095]
    - [-0.0073452195116216765, 0.9999727585590525, -0.0007279355223411334, -0.0030587146933711722]
    - [0.0038944766308488753, 0.0007565561891287445, 0.9999921303062861, -0.023605118842939803]
    - [0.0, 0.0, 0.0, 1.0]

Tracking:
  disable_mono: false
  motion_filter:
    init_thresh: 4.0
    thresh: 3.6
  frontend:
    keyframe_thresh: 4.0
    keep_kf_once_deleted: false
    frontend_thresh: 16.0
    frontend_window: 15
    frontend_radius: 1
    frontend_nms: 1
    mono_depth_alpha: 0.01
    imu_late_init_from: 20
  backend:
    backend_thresh: 22.0
    backend_radius: 2
    backend_nms: 3
    covis_thresh: 0.3
  pgba:
    active: true
    pgba_thresh: 22.0

Training:
  carve_lambda: 0.0
  carve_margin: 0.05
  n_global_views: 6
  parallel: true
  queue_size: 2
  init_itr_num: 600
  init_gaussian_update: 100
  init_gaussian_reset: 500
  init_gaussian_th: 0.005
  init_gaussian_extent: 30
  gaussian_update_every: 150
  gaussian_update_offset: 50
  gaussian_th: 0.7
  gaussian_extent: 1.0
  gaussian_reset: 2000000001
  size_threshold: 20
  window_size: 10
  rgb_boundary_threshold: 0.01
  lambda_dnormal: 0.5
  compensate_exposure: true
  kernel_batch_render: true
  background_polish: false
  background_polish_max_steps: 1500
  background_polish_idle_guard_ms: 5.0

opt_params:
  pose_lr: 0.0001
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_max_steps: 26000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.001
  rotation_lr: 0.001
  exposure_lr: 0.01
  percent_dense: 0.01
  lambda_dssim: 0.2
  densify_grad_threshold: 0.0002
